use strict;
use warnings;

package Spark::Types::Classes;

# ABSTRACT: MooseX::Types for all Spark Classes

# NOTE: This file is generated from the template Spark_Types_Classes.pm.tpl
# DO NOT EDIT THIS FILE.
# Last generated at Thu Dec 29 17:24:26 2011

use MooseX::Types -declare => [qw(
      Spark
      SparkHashray
      SparkList
      SparkLoad
      SparkRendererContainerForm
      SparkResult
      SparkResultItem
      SparkValidatorFieldMethod
      SparkValidatorNode
      SparkValidatorRegex
      SparkWheelButton
      SparkWheelButtonRendererHTML
      SparkWheelCheckbox
      SparkWheelCheckboxRendererHTML
      SparkWheelDummy
      SparkWheelDummyRendererHTML
      SparkWheelFile
      SparkWheelFileRendererHTML
      SparkWheelHidden
      SparkWheelHiddenRendererHTML
      SparkWheelImage
      SparkWheelImageRendererHTML
      SparkWheelMultiSelect
      SparkWheelMultiSelectRendererHTML
      SparkWheelPassword
      SparkWheelPasswordRendererHTML
      SparkWheelRadio
      SparkWheelRadioGroup
      SparkWheelRadioGroupRendererHTML
      SparkWheelRadioRendererHTML
      SparkWheelReset
      SparkWheelResetRendererHTML
      SparkWheelSelect
      SparkWheelSelectRendererHTML
      SparkWheelSubmit
      SparkWheelSubmitRendererHTML
      SparkWheelText
      SparkWheelTextRendererHTML
      SparkWheelTextarea
      SparkWheelTextareaRendererHTML
      )];
use namespace::autoclean;

=head1 TYPES



=head2 Spark

  isa => 'Spark'

=cut

class_type Spark, {
    class   => 'Spark',
    message => sub {
        return qq{$_ is not of class "Spark"};
    },
};

=head2 SparkHashray

  isa => 'Spark::Hashray'

=cut

class_type SparkHashray, {
    class   => 'Spark::Hashray',
    message => sub {
        return qq{$_ is not of class "Spark::Hashray"};
    },
};

=head2 SparkList

  isa => 'Spark::List'

=cut

class_type SparkList, {
    class   => 'Spark::List',
    message => sub {
        return qq{$_ is not of class "Spark::List"};
    },
};

=head2 SparkLoad

  isa => 'Spark::Load'

=cut

class_type SparkLoad, {
    class   => 'Spark::Load',
    message => sub {
        return qq{$_ is not of class "Spark::Load"};
    },
};

=head2 SparkRendererContainerForm

  isa => 'Spark::Renderer::Container::Form'

=cut

class_type SparkRendererContainerForm, {
    class   => 'Spark::Renderer::Container::Form',
    message => sub {
        return qq{$_ is not of class "Spark::Renderer::Container::Form"};
    },
};

=head2 SparkResult

  isa => 'Spark::Result'

=cut

class_type SparkResult, {
    class   => 'Spark::Result',
    message => sub {
        return qq{$_ is not of class "Spark::Result"};
    },
};

=head2 SparkResultItem

  isa => 'Spark::Result::Item'

=cut

class_type SparkResultItem, {
    class   => 'Spark::Result::Item',
    message => sub {
        return qq{$_ is not of class "Spark::Result::Item"};
    },
};

=head2 SparkValidatorFieldMethod

  isa => 'Spark::Validator::FieldMethod'

=cut

class_type SparkValidatorFieldMethod, {
    class   => 'Spark::Validator::FieldMethod',
    message => sub {
        return qq{$_ is not of class "Spark::Validator::FieldMethod"};
    },
};

=head2 SparkValidatorNode

  isa => 'Spark::Validator::Node'

=cut

class_type SparkValidatorNode, {
    class   => 'Spark::Validator::Node',
    message => sub {
        return qq{$_ is not of class "Spark::Validator::Node"};
    },
};

=head2 SparkValidatorRegex

  isa => 'Spark::Validator::Regex'

=cut

class_type SparkValidatorRegex, {
    class   => 'Spark::Validator::Regex',
    message => sub {
        return qq{$_ is not of class "Spark::Validator::Regex"};
    },
};

=head2 SparkWheelButton

  isa => 'Spark::Wheel::Button'

=cut

class_type SparkWheelButton, {
    class   => 'Spark::Wheel::Button',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Button"};
    },
};

=head2 SparkWheelButtonRendererHTML

  isa => 'Spark::Wheel::Button::Renderer::HTML'

=cut

class_type SparkWheelButtonRendererHTML, {
    class   => 'Spark::Wheel::Button::Renderer::HTML',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Button::Renderer::HTML"};
    },
};

=head2 SparkWheelCheckbox

  isa => 'Spark::Wheel::Checkbox'

=cut

class_type SparkWheelCheckbox, {
    class   => 'Spark::Wheel::Checkbox',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Checkbox"};
    },
};

=head2 SparkWheelCheckboxRendererHTML

  isa => 'Spark::Wheel::Checkbox::Renderer::HTML'

=cut

class_type SparkWheelCheckboxRendererHTML, {
    class   => 'Spark::Wheel::Checkbox::Renderer::HTML',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Checkbox::Renderer::HTML"};
    },
};

=head2 SparkWheelDummy

  isa => 'Spark::Wheel::Dummy'

=cut

class_type SparkWheelDummy, {
    class   => 'Spark::Wheel::Dummy',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Dummy"};
    },
};

=head2 SparkWheelDummyRendererHTML

  isa => 'Spark::Wheel::Dummy::Renderer::HTML'

=cut

class_type SparkWheelDummyRendererHTML, {
    class   => 'Spark::Wheel::Dummy::Renderer::HTML',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Dummy::Renderer::HTML"};
    },
};

=head2 SparkWheelFile

  isa => 'Spark::Wheel::File'

=cut

class_type SparkWheelFile, {
    class   => 'Spark::Wheel::File',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::File"};
    },
};

=head2 SparkWheelFileRendererHTML

  isa => 'Spark::Wheel::File::Renderer::HTML'

=cut

class_type SparkWheelFileRendererHTML, {
    class   => 'Spark::Wheel::File::Renderer::HTML',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::File::Renderer::HTML"};
    },
};

=head2 SparkWheelHidden

  isa => 'Spark::Wheel::Hidden'

=cut

class_type SparkWheelHidden, {
    class   => 'Spark::Wheel::Hidden',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Hidden"};
    },
};

=head2 SparkWheelHiddenRendererHTML

  isa => 'Spark::Wheel::Hidden::Renderer::HTML'

=cut

class_type SparkWheelHiddenRendererHTML, {
    class   => 'Spark::Wheel::Hidden::Renderer::HTML',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Hidden::Renderer::HTML"};
    },
};

=head2 SparkWheelImage

  isa => 'Spark::Wheel::Image'

=cut

class_type SparkWheelImage, {
    class   => 'Spark::Wheel::Image',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Image"};
    },
};

=head2 SparkWheelImageRendererHTML

  isa => 'Spark::Wheel::Image::Renderer::HTML'

=cut

class_type SparkWheelImageRendererHTML, {
    class   => 'Spark::Wheel::Image::Renderer::HTML',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Image::Renderer::HTML"};
    },
};

=head2 SparkWheelMultiSelect

  isa => 'Spark::Wheel::MultiSelect'

=cut

class_type SparkWheelMultiSelect, {
    class   => 'Spark::Wheel::MultiSelect',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::MultiSelect"};
    },
};

=head2 SparkWheelMultiSelectRendererHTML

  isa => 'Spark::Wheel::MultiSelect::Renderer::HTML'

=cut

class_type SparkWheelMultiSelectRendererHTML, {
    class   => 'Spark::Wheel::MultiSelect::Renderer::HTML',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::MultiSelect::Renderer::HTML"};
    },
};

=head2 SparkWheelPassword

  isa => 'Spark::Wheel::Password'

=cut

class_type SparkWheelPassword, {
    class   => 'Spark::Wheel::Password',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Password"};
    },
};

=head2 SparkWheelPasswordRendererHTML

  isa => 'Spark::Wheel::Password::Renderer::HTML'

=cut

class_type SparkWheelPasswordRendererHTML, {
    class   => 'Spark::Wheel::Password::Renderer::HTML',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Password::Renderer::HTML"};
    },
};

=head2 SparkWheelRadio

  isa => 'Spark::Wheel::Radio'

=cut

class_type SparkWheelRadio, {
    class   => 'Spark::Wheel::Radio',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Radio"};
    },
};

=head2 SparkWheelRadioGroup

  isa => 'Spark::Wheel::RadioGroup'

=cut

class_type SparkWheelRadioGroup, {
    class   => 'Spark::Wheel::RadioGroup',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::RadioGroup"};
    },
};

=head2 SparkWheelRadioGroupRendererHTML

  isa => 'Spark::Wheel::RadioGroup::Renderer::HTML'

=cut

class_type SparkWheelRadioGroupRendererHTML, {
    class   => 'Spark::Wheel::RadioGroup::Renderer::HTML',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::RadioGroup::Renderer::HTML"};
    },
};

=head2 SparkWheelRadioRendererHTML

  isa => 'Spark::Wheel::Radio::Renderer::HTML'

=cut

class_type SparkWheelRadioRendererHTML, {
    class   => 'Spark::Wheel::Radio::Renderer::HTML',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Radio::Renderer::HTML"};
    },
};

=head2 SparkWheelReset

  isa => 'Spark::Wheel::Reset'

=cut

class_type SparkWheelReset, {
    class   => 'Spark::Wheel::Reset',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Reset"};
    },
};

=head2 SparkWheelResetRendererHTML

  isa => 'Spark::Wheel::Reset::Renderer::HTML'

=cut

class_type SparkWheelResetRendererHTML, {
    class   => 'Spark::Wheel::Reset::Renderer::HTML',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Reset::Renderer::HTML"};
    },
};

=head2 SparkWheelSelect

  isa => 'Spark::Wheel::Select'

=cut

class_type SparkWheelSelect, {
    class   => 'Spark::Wheel::Select',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Select"};
    },
};

=head2 SparkWheelSelectRendererHTML

  isa => 'Spark::Wheel::Select::Renderer::HTML'

=cut

class_type SparkWheelSelectRendererHTML, {
    class   => 'Spark::Wheel::Select::Renderer::HTML',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Select::Renderer::HTML"};
    },
};

=head2 SparkWheelSubmit

  isa => 'Spark::Wheel::Submit'

=cut

class_type SparkWheelSubmit, {
    class   => 'Spark::Wheel::Submit',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Submit"};
    },
};

=head2 SparkWheelSubmitRendererHTML

  isa => 'Spark::Wheel::Submit::Renderer::HTML'

=cut

class_type SparkWheelSubmitRendererHTML, {
    class   => 'Spark::Wheel::Submit::Renderer::HTML',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Submit::Renderer::HTML"};
    },
};

=head2 SparkWheelText

  isa => 'Spark::Wheel::Text'

=cut

class_type SparkWheelText, {
    class   => 'Spark::Wheel::Text',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Text"};
    },
};

=head2 SparkWheelTextRendererHTML

  isa => 'Spark::Wheel::Text::Renderer::HTML'

=cut

class_type SparkWheelTextRendererHTML, {
    class   => 'Spark::Wheel::Text::Renderer::HTML',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Text::Renderer::HTML"};
    },
};

=head2 SparkWheelTextarea

  isa => 'Spark::Wheel::Textarea'

=cut

class_type SparkWheelTextarea, {
    class   => 'Spark::Wheel::Textarea',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Textarea"};
    },
};

=head2 SparkWheelTextareaRendererHTML

  isa => 'Spark::Wheel::Textarea::Renderer::HTML'

=cut

class_type SparkWheelTextareaRendererHTML, {
    class   => 'Spark::Wheel::Textarea::Renderer::HTML',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Textarea::Renderer::HTML"};
    },
};

1;
__END__
