use strict;
use warnings;

package Spark::Types::Classes;
{
  $Spark::Types::Classes::VERSION = '0.1.0';
}

# ABSTRACT: MooseX::Types for all Spark Classes

# NOTE: This file is generated from the template Spark_Types_Classes.pm.tpl
# DO NOT EDIT THIS FILE.
# Last generated at Thu Aug 25 09:33:06 2011

use MooseX::Types -declare => [qw(
      Spark
      SparkCollection
      SparkFormField
      SparkFormFieldResult
      SparkFormFieldValidatorResult
      SparkFormLoader
      SparkFormPluginLoader
      SparkFormResult
      SparkFormValidator
      SparkFormValidatorResult
      SparkHashray
      SparkLoad
      SparkRendererContainerForm
      SparkResult
      SparkResultItem
      SparkValidatesWithValidators
      SparkValidatorNode
      SparkValidatorRegex
      SparkWheelButton
      SparkWheelButtonRendererHTML
      SparkWheelCheckbox
      SparkWheelCheckboxRendererHTML
      SparkWheelDummy
      SparkWheelDummyRendererHTML
      SparkWheelFile
      SparkWheelFileRendererHTML
      SparkWheelHidden
      SparkWheelHiddenRendererHTML
      SparkWheelImage
      SparkWheelImageRendererHTML
      SparkWheelMultiSelect
      SparkWheelMultiSelectRendererHTML
      SparkWheelPassword
      SparkWheelPasswordRendererHTML
      SparkWheelRadio
      SparkWheelRadioGroup
      SparkWheelRadioGroupRendererHTML
      SparkWheelRadioRendererHTML
      SparkWheelReset
      SparkWheelResetRendererHTML
      SparkWheelSelect
      SparkWheelSelectRendererHTML
      SparkWheelSubmit
      SparkWheelSubmitRendererHTML
      SparkWheelText
      SparkWheelTextRendererHTML
      SparkWheelTextarea
      SparkWheelTextareaRendererHTML
      )];
use namespace::autoclean;


class_type Spark, {
    class   => 'Spark',
    message => sub {
        return qq{$_ is not of class "Spark"};
    },
};


class_type SparkCollection, {
    class   => 'Spark::Collection',
    message => sub {
        return qq{$_ is not of class "Spark::Collection"};
    },
};


class_type SparkFormField, {
    class   => 'Spark::Form::Field',
    message => sub {
        return qq{$_ is not of class "Spark::Form::Field"};
    },
};


class_type SparkFormFieldResult, {
    class   => 'Spark::Form::Field::Result',
    message => sub {
        return qq{$_ is not of class "Spark::Form::Field::Result"};
    },
};


class_type SparkFormFieldValidatorResult, {
    class   => 'Spark::Form::Field::Validator::Result',
    message => sub {
        return qq{$_ is not of class "Spark::Form::Field::Validator::Result"};
    },
};


class_type SparkFormLoader, {
    class   => 'Spark::Form::Loader',
    message => sub {
        return qq{$_ is not of class "Spark::Form::Loader"};
    },
};


class_type SparkFormPluginLoader, {
    class   => 'Spark::Form::PluginLoader',
    message => sub {
        return qq{$_ is not of class "Spark::Form::PluginLoader"};
    },
};


class_type SparkFormResult, {
    class   => 'Spark::Form::Result',
    message => sub {
        return qq{$_ is not of class "Spark::Form::Result"};
    },
};


class_type SparkFormValidator, {
    class   => 'Spark::Form::Validator',
    message => sub {
        return qq{$_ is not of class "Spark::Form::Validator"};
    },
};


class_type SparkFormValidatorResult, {
    class   => 'Spark::Form::Validator::Result',
    message => sub {
        return qq{$_ is not of class "Spark::Form::Validator::Result"};
    },
};


class_type SparkHashray, {
    class   => 'Spark::Hashray',
    message => sub {
        return qq{$_ is not of class "Spark::Hashray"};
    },
};


class_type SparkLoad, {
    class   => 'Spark::Load',
    message => sub {
        return qq{$_ is not of class "Spark::Load"};
    },
};


class_type SparkRendererContainerForm, {
    class   => 'Spark::Renderer::Container::Form',
    message => sub {
        return qq{$_ is not of class "Spark::Renderer::Container::Form"};
    },
};


class_type SparkResult, {
    class   => 'Spark::Result',
    message => sub {
        return qq{$_ is not of class "Spark::Result"};
    },
};


class_type SparkResultItem, {
    class   => 'Spark::Result::Item',
    message => sub {
        return qq{$_ is not of class "Spark::Result::Item"};
    },
};


class_type SparkValidatesWithValidators, {
    class   => 'Spark::Validates::WithValidators',
    message => sub {
        return qq{$_ is not of class "Spark::Validates::WithValidators"};
    },
};


class_type SparkValidatorNode, {
    class   => 'Spark::Validator::Node',
    message => sub {
        return qq{$_ is not of class "Spark::Validator::Node"};
    },
};


class_type SparkValidatorRegex, {
    class   => 'Spark::Validator::Regex',
    message => sub {
        return qq{$_ is not of class "Spark::Validator::Regex"};
    },
};


class_type SparkWheelButton, {
    class   => 'Spark::Wheel::Button',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Button"};
    },
};


class_type SparkWheelButtonRendererHTML, {
    class   => 'Spark::Wheel::Button::Renderer::HTML',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Button::Renderer::HTML"};
    },
};


class_type SparkWheelCheckbox, {
    class   => 'Spark::Wheel::Checkbox',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Checkbox"};
    },
};


class_type SparkWheelCheckboxRendererHTML, {
    class   => 'Spark::Wheel::Checkbox::Renderer::HTML',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Checkbox::Renderer::HTML"};
    },
};


class_type SparkWheelDummy, {
    class   => 'Spark::Wheel::Dummy',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Dummy"};
    },
};


class_type SparkWheelDummyRendererHTML, {
    class   => 'Spark::Wheel::Dummy::Renderer::HTML',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Dummy::Renderer::HTML"};
    },
};


class_type SparkWheelFile, {
    class   => 'Spark::Wheel::File',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::File"};
    },
};


class_type SparkWheelFileRendererHTML, {
    class   => 'Spark::Wheel::File::Renderer::HTML',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::File::Renderer::HTML"};
    },
};


class_type SparkWheelHidden, {
    class   => 'Spark::Wheel::Hidden',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Hidden"};
    },
};


class_type SparkWheelHiddenRendererHTML, {
    class   => 'Spark::Wheel::Hidden::Renderer::HTML',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Hidden::Renderer::HTML"};
    },
};


class_type SparkWheelImage, {
    class   => 'Spark::Wheel::Image',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Image"};
    },
};


class_type SparkWheelImageRendererHTML, {
    class   => 'Spark::Wheel::Image::Renderer::HTML',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Image::Renderer::HTML"};
    },
};


class_type SparkWheelMultiSelect, {
    class   => 'Spark::Wheel::MultiSelect',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::MultiSelect"};
    },
};


class_type SparkWheelMultiSelectRendererHTML, {
    class   => 'Spark::Wheel::MultiSelect::Renderer::HTML',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::MultiSelect::Renderer::HTML"};
    },
};


class_type SparkWheelPassword, {
    class   => 'Spark::Wheel::Password',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Password"};
    },
};


class_type SparkWheelPasswordRendererHTML, {
    class   => 'Spark::Wheel::Password::Renderer::HTML',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Password::Renderer::HTML"};
    },
};


class_type SparkWheelRadio, {
    class   => 'Spark::Wheel::Radio',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Radio"};
    },
};


class_type SparkWheelRadioGroup, {
    class   => 'Spark::Wheel::RadioGroup',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::RadioGroup"};
    },
};


class_type SparkWheelRadioGroupRendererHTML, {
    class   => 'Spark::Wheel::RadioGroup::Renderer::HTML',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::RadioGroup::Renderer::HTML"};
    },
};


class_type SparkWheelRadioRendererHTML, {
    class   => 'Spark::Wheel::Radio::Renderer::HTML',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Radio::Renderer::HTML"};
    },
};


class_type SparkWheelReset, {
    class   => 'Spark::Wheel::Reset',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Reset"};
    },
};


class_type SparkWheelResetRendererHTML, {
    class   => 'Spark::Wheel::Reset::Renderer::HTML',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Reset::Renderer::HTML"};
    },
};


class_type SparkWheelSelect, {
    class   => 'Spark::Wheel::Select',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Select"};
    },
};


class_type SparkWheelSelectRendererHTML, {
    class   => 'Spark::Wheel::Select::Renderer::HTML',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Select::Renderer::HTML"};
    },
};


class_type SparkWheelSubmit, {
    class   => 'Spark::Wheel::Submit',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Submit"};
    },
};


class_type SparkWheelSubmitRendererHTML, {
    class   => 'Spark::Wheel::Submit::Renderer::HTML',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Submit::Renderer::HTML"};
    },
};


class_type SparkWheelText, {
    class   => 'Spark::Wheel::Text',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Text"};
    },
};


class_type SparkWheelTextRendererHTML, {
    class   => 'Spark::Wheel::Text::Renderer::HTML',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Text::Renderer::HTML"};
    },
};


class_type SparkWheelTextarea, {
    class   => 'Spark::Wheel::Textarea',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Textarea"};
    },
};


class_type SparkWheelTextareaRendererHTML, {
    class   => 'Spark::Wheel::Textarea::Renderer::HTML',
    message => sub {
        return qq{$_ is not of class "Spark::Wheel::Textarea::Renderer::HTML"};
    },
};

1;


=pod

=encoding utf-8

=head1 NAME

Spark::Types::Classes - MooseX::Types for all Spark Classes

=head1 VERSION

version 0.1.0

=head1 TYPES

=head2 Spark

  isa => 'Spark'

=head2 SparkCollection

  isa => 'Spark::Collection'

=head2 SparkFormField

  isa => 'Spark::Form::Field'

=head2 SparkFormFieldResult

  isa => 'Spark::Form::Field::Result'

=head2 SparkFormFieldValidatorResult

  isa => 'Spark::Form::Field::Validator::Result'

=head2 SparkFormLoader

  isa => 'Spark::Form::Loader'

=head2 SparkFormPluginLoader

  isa => 'Spark::Form::PluginLoader'

=head2 SparkFormResult

  isa => 'Spark::Form::Result'

=head2 SparkFormValidator

  isa => 'Spark::Form::Validator'

=head2 SparkFormValidatorResult

  isa => 'Spark::Form::Validator::Result'

=head2 SparkHashray

  isa => 'Spark::Hashray'

=head2 SparkLoad

  isa => 'Spark::Load'

=head2 SparkRendererContainerForm

  isa => 'Spark::Renderer::Container::Form'

=head2 SparkResult

  isa => 'Spark::Result'

=head2 SparkResultItem

  isa => 'Spark::Result::Item'

=head2 SparkValidatesWithValidators

  isa => 'Spark::Validates::WithValidators'

=head2 SparkValidatorNode

  isa => 'Spark::Validator::Node'

=head2 SparkValidatorRegex

  isa => 'Spark::Validator::Regex'

=head2 SparkWheelButton

  isa => 'Spark::Wheel::Button'

=head2 SparkWheelButtonRendererHTML

  isa => 'Spark::Wheel::Button::Renderer::HTML'

=head2 SparkWheelCheckbox

  isa => 'Spark::Wheel::Checkbox'

=head2 SparkWheelCheckboxRendererHTML

  isa => 'Spark::Wheel::Checkbox::Renderer::HTML'

=head2 SparkWheelDummy

  isa => 'Spark::Wheel::Dummy'

=head2 SparkWheelDummyRendererHTML

  isa => 'Spark::Wheel::Dummy::Renderer::HTML'

=head2 SparkWheelFile

  isa => 'Spark::Wheel::File'

=head2 SparkWheelFileRendererHTML

  isa => 'Spark::Wheel::File::Renderer::HTML'

=head2 SparkWheelHidden

  isa => 'Spark::Wheel::Hidden'

=head2 SparkWheelHiddenRendererHTML

  isa => 'Spark::Wheel::Hidden::Renderer::HTML'

=head2 SparkWheelImage

  isa => 'Spark::Wheel::Image'

=head2 SparkWheelImageRendererHTML

  isa => 'Spark::Wheel::Image::Renderer::HTML'

=head2 SparkWheelMultiSelect

  isa => 'Spark::Wheel::MultiSelect'

=head2 SparkWheelMultiSelectRendererHTML

  isa => 'Spark::Wheel::MultiSelect::Renderer::HTML'

=head2 SparkWheelPassword

  isa => 'Spark::Wheel::Password'

=head2 SparkWheelPasswordRendererHTML

  isa => 'Spark::Wheel::Password::Renderer::HTML'

=head2 SparkWheelRadio

  isa => 'Spark::Wheel::Radio'

=head2 SparkWheelRadioGroup

  isa => 'Spark::Wheel::RadioGroup'

=head2 SparkWheelRadioGroupRendererHTML

  isa => 'Spark::Wheel::RadioGroup::Renderer::HTML'

=head2 SparkWheelRadioRendererHTML

  isa => 'Spark::Wheel::Radio::Renderer::HTML'

=head2 SparkWheelReset

  isa => 'Spark::Wheel::Reset'

=head2 SparkWheelResetRendererHTML

  isa => 'Spark::Wheel::Reset::Renderer::HTML'

=head2 SparkWheelSelect

  isa => 'Spark::Wheel::Select'

=head2 SparkWheelSelectRendererHTML

  isa => 'Spark::Wheel::Select::Renderer::HTML'

=head2 SparkWheelSubmit

  isa => 'Spark::Wheel::Submit'

=head2 SparkWheelSubmitRendererHTML

  isa => 'Spark::Wheel::Submit::Renderer::HTML'

=head2 SparkWheelText

  isa => 'Spark::Wheel::Text'

=head2 SparkWheelTextRendererHTML

  isa => 'Spark::Wheel::Text::Renderer::HTML'

=head2 SparkWheelTextarea

  isa => 'Spark::Wheel::Textarea'

=head2 SparkWheelTextareaRendererHTML

  isa => 'Spark::Wheel::Textarea::Renderer::HTML'

=head1 AUTHORS

=over 4

=item *

James Laver L<http://jameslaver.com>

=item *

Kent Fredric <kentnl@cpan.org>

=item *

Paweł Murias <pawelmurias@gmail.com>

=item *

David Dorward <david@dorward.me.uk>

=back

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2011 by James Laver C<< <sprintf qw(%s@%s.%s cpan jameslaver com)> >>.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

=cut


__END__
